## 주문 신규 생성

POST localhost:8080/api/v1/booking
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyVXVpZCI6IjliMGI0ODdhLTY2NzAtNDU0MS1iYjc0LTgzZDVkZWE5OGRhYSIsImVtYWlsIjoiYUBhLmNvbSIsIm51bWJlciI6MCwiZXhwaXJlQXQiOjE3MDM3MTIxMzgsInN0YXR1cyI6IlZBTElEIiwidG9rZW5TdHJpbmciOm51bGx9.ipcXirQBPPlHRl_vc-z-2ovd_sngKwZgVTPnwni2AzA

{
  "seatId" : 1
}
