spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybackenddb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    defer-datasource-initialization: true
    open-in-view: false

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.MySQLDialect

  sql:
    init:
      mode: always


management:
  endpoint:
    health:
      show-details: always

logging.level:
  com.my: info
  org.springframework:
    web: debug
    boot.jdbc: debug
  org.hibernate.SQL: debug
  org.hibernate.type.descriptor: trace

---
spring:
  config:
    activate:
      on-profile: dev
    import: classpath:/properties/application-dev.yml
