spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybackenddb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.MySQLDialect

management:
  endpoint:
    health:
      show-details: always

jwt:
  secret-key: Thesailingplustaskisverydifficult

logging.level:
  com.my: info
  org.springframework.web: debug
  org.hibernate.SQL: debug
  org.hibernate.type.descriptor: trace

---
spring:
  config:
    activate:
      on-profile: dev
    import: classpath:/properties/application-dev.yml
