GET localhost:8080/api/v1/pays/balance
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyVXVpZCI6ImYwNGIxMDQ3LTM1NTctNDY3Yy04NzNmLTAxNTRhMmRjOGQyZCIsImVtYWlsIjoiYUBhLmNvbSIsIm51bWJlciI6MCwiZXhwaXJlQXQiOjE3MDM3MDczMTcsInN0YXR1cyI6IlZBTElEIiwidG9rZW5TdHJpbmciOm51bGx9.ve_UY0_BatF4Iu1923pE3YtN6PSY11a4wMTUiCUeXx0
